#!/bin/bash

# ln -s ~/dotfiles/user/.bash_profile ~/.bash_profile
# cp ssh/config ~/.ssh/config
ln -s ~/dotfiles/vim/.vimrc ~/.vimrc
# cp vim/plugins.vim ~/.vim/plugins.vim
# cp vim/settings.vim ~/.vim/settings.vim
